# This is just an example!
services:
  caddy:
    image: "ghcr.io/steve-taylor/caddy-static-vhost:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/opt/www/:/opt/www/"
      - "caddy_data:/data"
      - "caddy_config:/config"
    environment:
      - "HOSTNAME=example.net"
      - "MARKETING_URL=https://example.com"
      - "DNS_CHECK_ENDPOINT=https://api.example.com/dnscheck"
      - "DIGITALOCEAN_DNS_API_TOKEN:${DIGITALOCEAN_DNS_API_TOKEN}" # provided externally
volumes:
  caddy_data:
    external: true
  caddy_config:
