name: Docker

description: Combine Docker actions with sensible defaults

runs:
  using: composite
  steps:
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{github.repository}}
        tags: |
          type=raw,value=latest,enable=${{github.ref == format('refs/heads/{0}', github.event.repository.default_branch)}}
          type=semver,pattern={{version}},enable=${{github.event.action == 'published'}}

    - name: Build Docker image and push on release
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{github.event.action == 'published'}}
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
